#!/bin/bash
case "$1" in

	build)
	echo Building for macOS..
	cp src/mac-config.php src/config.php
	docker build -t mach-mongoqp .
	echo
	echo ">> Now you can run: $0 start"
	echo
	;;

	build-linux)
	echo Building for linux..
	cp src/linux-config.php src/config.php
	docker build -t mach-mongoqp .
	;;

	start)
	params=""
	PORT=8888
	[ -n "$2" ] && params="-e URI=$2"
	[ -n "$3" ] && params="$params -e PORT=$3" && PORT=$3
	echo params $params port $PORT or $3
	docker run -d -p${PORT}:${PORT} --name mach-mongoqp $params mach-mongoqp php -S0:${PORT} -t web
	echo
	echo ">> mongoqp running at http://localhost:8888"
	echo
	;;

	stop)
	docker stop mach-mongoqp -t1
	docker rm mach-mongoqp
	;;

	*)
	echo "Usage: $0 (build | start | stop)"
	echo "start takes 2 optional parameters: <URI> <PORT>"
esac
